version: '0.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9643:9643
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/todo_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres